name: Deploy to cloud

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: (Frontend) Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.FRONTEND_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.FRONTEND_SSHKEY }}
      with:
        source: "."
        target: "/home/rails/service-api-example"

    - name: (Frontend) Bundle and restart app server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.FRONTEND_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.FRONTEND_SSHKEY }}
        script: |
          su - rails -c "cd /home/rails/service-api-example/frontend-sinatra && bundle"
          sudo systemctl restart rails.service
    - name: (Service API) Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.API_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.API_SSHKEY }}
      with:
        source: "."
        target: "/home/rails/service-api-example"

    - name: (Service API) Bundle and restart app server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.API_HOST }}
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.API_SSHKEY }}
        script: |
          su - rails -c "cd /home/rails/service-api-example/service-api-sinatra && bundle"
          sudo systemctl restart rails.service
